package gowhere

var Countries = []Country{
	Country{
		Code:           "AF",
		Currency:       "AFN",
		CurrencySymbol: "؋",
		Phone:          "+93",
		Name:           "Afghanistan",
	},
	Country{
		Code:           "AL",
		Currency:       "ALL",
		CurrencySymbol: "L",
		Phone:          "+355",
		Name:           "Albania",
	},
	Country{
		Code:           "DZ",
		Currency:       "DZD",
		CurrencySymbol: "دج",
		Phone:          "+213",
		Name:           "Algeria",
	},
	Country{
		Code:           "AS",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1684",
		Name:           "American Samoa",
	},
	Country{
		Code:           "AD",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+376",
		Name:           "Andorra",
	},
	Country{
		Code:           "AO",
		Currency:       "AOA",
		CurrencySymbol: "Kz",
		Phone:          "+244",
		Name:           "Angola",
	},
	Country{
		Code:           "AI",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1264",
		Name:           "Anguilla",
	},
	Country{
		Code:           "AQ",
		Currency:       "",
		CurrencySymbol: "$",
		Phone:          "+672",
		Name:           "Antarctica",
	},
	Country{
		Code:           "AG",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1268",
		Name:           "Antigua and Barbuda",
	},
	Country{
		Code:           "AR",
		Currency:       "ARS",
		CurrencySymbol: "$",
		Phone:          "+54",
		Name:           "Argentina",
	},
	Country{
		Code:           "AM",
		Currency:       "AMD",
		CurrencySymbol: "֏",
		Phone:          "+374",
		Name:           "Armenia",
	},
	Country{
		Code:           "AW",
		Currency:       "AWG",
		CurrencySymbol: "ƒ",
		Phone:          "+297",
		Name:           "Aruba",
	},
	Country{
		Code:           "AU",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+61",
		Name:           "Australia",
	},
	Country{
		Code:           "AT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+43",
		Name:           "Austria",
	},
	Country{
		Code:           "AZ",
		Currency:       "AZN",
		CurrencySymbol: "₼",
		Phone:          "+994",
		Name:           "Azerbaijan",
	},
	Country{
		Code:           "BH",
		Currency:       "BHD",
		CurrencySymbol: ".د.ب",
		Phone:          "+973",
		Name:           "Bahrain",
	},
	Country{
		Code:           "BS",
		Currency:       "BSD",
		CurrencySymbol: "$",
		Phone:          "+1242",
		Name:           "The Bahamas",
	},
	Country{
		Code:           "BD",
		Currency:       "BDT",
		CurrencySymbol: "৳",
		Phone:          "+880",
		Name:           "Bangladesh",
	},
	Country{
		Code:           "BB",
		Currency:       "BBD",
		CurrencySymbol: "$",
		Phone:          "+1 246",
		Name:           "Barbados",
	},
	Country{
		Code:           "BY",
		Currency:       "BYR",
		CurrencySymbol: "Br",
		Phone:          "+375",
		Name:           "Belarus",
	},
	Country{
		Code:           "BE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+32",
		Name:           "Belgium",
	},
	Country{
		Code:           "BZ",
		Currency:       "BZD",
		CurrencySymbol: "BZ$",
		Phone:          "+501",
		Name:           "Belize",
	},
	Country{
		Code:           "BJ",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+229",
		Name:           "Benin",
	},
	Country{
		Code:           "BM",
		Currency:       "BMD",
		CurrencySymbol: "$",
		Phone:          "+1441",
		Name:           "Bermuda",
	},
	Country{
		Code:           "BT",
		Currency:       "BTN",
		CurrencySymbol: "Nu.",
		Phone:          "+975",
		Name:           "Bhutan",
	},
	Country{
		Code:           "BO",
		Currency:       "BOB",
		CurrencySymbol: "$b",
		Phone:          "+591",
		Name:           "Bolivia",
	},
	Country{
		Code:           "BQ",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+599",
		Name:           "Bonaire",
	},
	Country{
		Code:           "BA",
		Currency:       "BAM",
		CurrencySymbol: "KM",
		Phone:          "+387",
		Name:           "Bosnia and Herzegovina",
	},
	Country{
		Code:           "BW",
		Currency:       "BWP",
		CurrencySymbol: "P",
		Phone:          "+267",
		Name:           "Botswana",
	},
	Country{
		Code:           "BV",
		Currency:       "NOK",
		CurrencySymbol: "kr",
		Phone:          "+47",
		Name:           "Bouvet",
	},
	Country{
		Code:           "BR",
		Currency:       "BRL",
		CurrencySymbol: "R$",
		Phone:          "+55",
		Name:           "Brazil",
	},
	Country{
		Code:           "IO",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+246",
		Name:           "British Indian Ocean Territory",
	},
	Country{
		Code:           "VG",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1284",
		Name:           "British Virgin Islands",
	},
	Country{
		Code:           "BN",
		Currency:       "BND",
		CurrencySymbol: "$",
		Phone:          "+673",
		Name:           "Brunei",
	},
	Country{
		Code:           "BG",
		Currency:       "BGN",
		CurrencySymbol: "лв",
		Phone:          "+359",
		Name:           "Bulgaria",
	},
	Country{
		Code:           "BF",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+226",
		Name:           "Burkina Faso",
	},
	Country{
		Code:           "MM",
		Currency:       "MMK",
		CurrencySymbol: "K",
		Phone:          "+95",
		Name:           "Myanmar",
	},
	Country{
		Code:           "BI",
		Currency:       "BIF",
		CurrencySymbol: "FBu",
		Phone:          "+257",
		Name:           "Burundi",
	},
	Country{
		Code:           "KH",
		Currency:       "KHR",
		CurrencySymbol: "៛",
		Phone:          "+855",
		Name:           "Cambodia",
	},
	Country{
		Code:           "CM",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+237",
		Name:           "Cameroon",
	},
	Country{
		Code:           "CA",
		Currency:       "CAD",
		CurrencySymbol: "$",
		Phone:          "+1",
		Name:           "Canada",
	},
	Country{
		Code:           "CV",
		Currency:       "CVE",
		CurrencySymbol: "$",
		Phone:          "+238",
		Name:           "Cape Verde",
	},
	Country{
		Code:           "KY",
		Currency:       "KYD",
		CurrencySymbol: "$",
		Phone:          "+1345",
		Name:           "Cayman Islands",
	},
	Country{
		Code:           "CF",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+236",
		Name:           "Central African Republic",
	},
	Country{
		Code:           "TD",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+235",
		Name:           "Chad",
	},
	Country{
		Code:           "CL",
		Currency:       "CLP",
		CurrencySymbol: "$",
		Phone:          "+56",
		Name:           "Chile",
	},
	Country{
		Code:           "CN",
		Currency:       "CNY",
		CurrencySymbol: "¥",
		Phone:          "+86",
		Name:           "China",
	},
	Country{
		Code:           "CX",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+61",
		Name:           "Christmas Island",
	},
	Country{
		Code:           "CC",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+672",
		Name:           "Cocos-Keeling Islands",
	},
	Country{
		Code:           "CO",
		Currency:       "COP",
		CurrencySymbol: "$",
		Phone:          "+57",
		Name:           "Colombia",
	},
	Country{
		Code:           "KM",
		Currency:       "KMF",
		CurrencySymbol: "CF",
		Phone:          "+269",
		Name:           "Comoros",
	},
	Country{
		Code:           "CG",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+242",
		Name:           "Congo",
	},
	Country{
		Code:           "CD",
		Currency:       "CDF",
		CurrencySymbol: "FC",
		Phone:          "+243",
		Name:           "Congo, Dem. Rep. of (Zaire)",
	},
	Country{
		Code:           "CK",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+682",
		Name:           "Cook Islands",
	},
	Country{
		Code:           "CR",
		Currency:       "CRC",
		CurrencySymbol: "₡",
		Phone:          "+506",
		Name:           "Costa Rica",
	},
	Country{
		Code:           "CI",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+225",
		Name:           "Cote d'Ivoire",
	},
	Country{
		Code:           "HR",
		Currency:       "HRK",
		CurrencySymbol: "kn",
		Phone:          "+385",
		Name:           "Croatia",
	},
	Country{
		Code:           "CW",
		Currency:       "ANG",
		CurrencySymbol: "ƒ",
		Phone:          "+599",
		Name:           "Curacao",
	},
	Country{
		Code:           "CU",
		Currency:       "CUP",
		CurrencySymbol: "₱",
		Phone:          "+53",
		Name:           "Cuba",
	},
	Country{
		Code:           "CY",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+357",
		Name:           "Cyprus",
	},
	Country{
		Code:           "CZ",
		Currency:       "CZK",
		CurrencySymbol: "Kč",
		Phone:          "+420",
		Name:           "Czech Republic",
	},
	Country{
		Code:           "DK",
		Currency:       "DKK",
		CurrencySymbol: "kr",
		Phone:          "+45",
		Name:           "Denmark",
	},
	Country{
		Code:           "DJ",
		Currency:       "DJF",
		CurrencySymbol: "Fdj",
		Phone:          "+253",
		Name:           "Djibouti",
	},
	Country{
		Code:           "DM",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1767",
		Name:           "Dominica",
	},
	Country{
		Code:           "DO",
		Currency:       "DOP",
		CurrencySymbol: "RD$",
		Phone:          "+1809",
		Name:           "Dominican Republic",
	},
	Country{
		Code:           "TL",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+670",
		Name:           "East Timor",
	},
	Country{
		Code:           "EC",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+593",
		Name:           "Ecuador",
	},
	Country{
		Code:           "EG",
		Currency:       "EGP",
		CurrencySymbol: "£",
		Phone:          "+20",
		Name:           "Egypt",
	},
	Country{
		Code:           "SV",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+503",
		Name:           "El Salvador",
	},
	Country{
		Code:           "GQ",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+240",
		Name:           "Equatorial Guinea",
	},
	Country{
		Code:           "ER",
		Currency:       "ERN",
		CurrencySymbol: "Nfk",
		Phone:          "+291",
		Name:           "Eritrea",
	},
	Country{
		Code:           "EE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+372",
		Name:           "Estonia",
	},
	Country{
		Code:           "ET",
		Currency:       "ETB",
		CurrencySymbol: "Br",
		Phone:          "+251",
		Name:           "Ethiopia",
	},
	Country{
		Code:           "FK",
		Currency:       "FKP",
		CurrencySymbol: "£",
		Phone:          "+500",
		Name:           "Falkland Islands",
	},
	Country{
		Code:           "FO",
		Currency:       "DKK",
		CurrencySymbol: "kr",
		Phone:          "+679",
		Name:           "Fiji",
	},
	Country{
		Code:           "FI",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+358",
		Name:           "Finland",
	},
	Country{
		Code:           "FR",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+33",
		Name:           "France",
	},
	Country{
		Code:           "GF",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+594",
		Name:           "French Guiana",
	},
	Country{
		Code:           "PF",
		Currency:       "XPF",
		CurrencySymbol: "₣",
		Phone:          "+689",
		Name:           "French Polynesia",
	},
	Country{
		Code:           "TF",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+262",
		Name:           "French Southern and Antarctic Lands",
	},
	Country{
		Code:           "GA",
		Currency:       "XAF",
		CurrencySymbol: "FCFA",
		Phone:          "+241",
		Name:           "Gabon",
	},
	Country{
		Code:           "GM",
		Currency:       "GMD",
		CurrencySymbol: "D",
		Phone:          "+220",
		Name:           "The Gambia",
	},
	Country{
		Code:           "GE",
		Currency:       "GEL",
		CurrencySymbol: "₾",
		Phone:          "+995",
		Name:           "Georgia",
	},
	Country{
		Code:           "DE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+49",
		Name:           "Germany",
	},
	Country{
		Code:           "GH",
		Currency:       "GHS",
		CurrencySymbol: "GH₵",
		Phone:          "+233",
		Name:           "Ghana",
	},
	Country{
		Code:           "GR",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+30",
		Name:           "Greece",
	},
	Country{
		Code:           "GL",
		Currency:       "DKK",
		CurrencySymbol: "kr",
		Phone:          "+299",
		Name:           "Greenland",
	},
	Country{
		Code:           "GD",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1473",
		Name:           "Grenada",
	},
	Country{
		Code:           "GP",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+590",
		Name:           "Guadeloupe",
	},
	Country{
		Code:           "GU",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1671",
		Name:           "Guam",
	},
	Country{
		Code:           "GT",
		Currency:       "GTQ",
		CurrencySymbol: "Q",
		Phone:          "+502",
		Name:           "Guatemala",
	},
	Country{
		Code:           "GG",
		Currency:       "GBP",
		CurrencySymbol: "£",
		Phone:          "+44",
		Name:           "Guernsey",
	},
	Country{
		Code:           "GN",
		Currency:       "GNF",
		CurrencySymbol: "FG",
		Phone:          "+224",
		Name:           "Guinea",
	},
	Country{
		Code:           "GW",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+245",
		Name:           "Guinea-Bissau",
	},
	Country{
		Code:           "GY",
		Currency:       "GYD",
		CurrencySymbol: "$",
		Phone:          "+592",
		Name:           "Guyana",
	},
	Country{
		Code:           "HT",
		Currency:       "HTG",
		CurrencySymbol: "G",
		Phone:          "+509",
		Name:           "Haiti",
	},
	Country{
		Code:           "HM",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+0",
		Name:           "Heard Island and McDonald Islands",
	},
	Country{
		Code:           "VA",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+39",
		Name:           "Holy See (Vatican City)",
	},
	Country{
		Code:           "HN",
		Currency:       "HNL",
		CurrencySymbol: "L",
		Phone:          "+504",
		Name:           "Honduras",
	},
	Country{
		Code:           "HK",
		Currency:       "HKD",
		CurrencySymbol: "$",
		Phone:          "+852",
		Name:           "Hong Kong SAR China",
	},
	Country{
		Code:           "HU",
		Currency:       "HUF",
		CurrencySymbol: "Ft",
		Phone:          "+36",
		Name:           "Hungary",
	},
	Country{
		Code:           "IS",
		Currency:       "ISK",
		CurrencySymbol: "kr",
		Phone:          "+354",
		Name:           "Iceland",
	},
	Country{
		Code:           "IN",
		Currency:       "INR",
		CurrencySymbol: "₹",
		Phone:          "+91",
		Name:           "India",
	},
	Country{
		Code:           "ID",
		Currency:       "IDR",
		CurrencySymbol: "Rp",
		Phone:          "+62",
		Name:           "Indonesia",
	},
	Country{
		Code:           "IR",
		Currency:       "IRR",
		CurrencySymbol: "﷼",
		Phone:          "+98",
		Name:           "Iran",
	},
	Country{
		Code:           "IQ",
		Currency:       "IQD",
		CurrencySymbol: "ع.د",
		Phone:          "+964",
		Name:           "Iraq",
	},
	Country{
		Code:           "IE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+353",
		Name:           "Ireland",
	},
	Country{
		Code:           "IM",
		Currency:       "GBP",
		CurrencySymbol: "£",
		Phone:          "+44",
		Name:           "Isle of Man",
	},
	Country{
		Code:           "IL",
		Currency:       "ILS",
		CurrencySymbol: "₪",
		Phone:          "+972",
		Name:           "Israel",
	},
	Country{
		Code:           "IT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+39",
		Name:           "Italy",
	},
	Country{
		Code:           "JM",
		Currency:       "JMD",
		CurrencySymbol: "J$",
		Phone:          "+1876",
		Name:           "Jamaica",
	},
	Country{
		Code:           "JP",
		Currency:       "JPY",
		CurrencySymbol: "¥",
		Phone:          "+81",
		Name:           "Japan",
	},
	Country{
		Code:           "JO",
		Currency:       "JOD",
		CurrencySymbol: "JD",
		Phone:          "+962",
		Name:           "Jordan",
	},
	Country{
		Code:           "KZ",
		Currency:       "KZT",
		CurrencySymbol: "лв",
		Phone:          "+7",
		Name:           "Kazakhstan",
	},
	Country{
		Code:           "KE",
		Currency:       "KES",
		CurrencySymbol: "KSh",
		Phone:          "+254",
		Name:           "Kenya",
	},
	Country{
		Code:           "KI",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+686",
		Name:           "Kiribati",
	},
	Country{
		Code:           "KW",
		Currency:       "KWD",
		CurrencySymbol: "KD",
		Phone:          "+965",
		Name:           "Kuwait",
	},
	Country{
		Code:           "KG",
		Currency:       "KGS",
		CurrencySymbol: "лв",
		Phone:          "+996",
		Name:           "Kyrgyzstan",
	},
	Country{
		Code:           "LA",
		Currency:       "LAK",
		CurrencySymbol: "₭",
		Phone:          "+856",
		Name:           "Laos",
	},
	Country{
		Code:           "LV",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+371",
		Name:           "Latvia",
	},
	Country{
		Code:           "LB",
		Currency:       "LBP",
		CurrencySymbol: "£",
		Phone:          "+961",
		Name:           "Lebanon",
	},
	Country{
		Code:           "LS",
		Currency:       "LSL",
		CurrencySymbol: "M",
		Phone:          "+266",
		Name:           "Lesotho",
	},
	Country{
		Code:           "LR",
		Currency:       "LRD",
		CurrencySymbol: "$",
		Phone:          "+231",
		Name:           "Liberia",
	},
	Country{
		Code:           "LY",
		Currency:       "LYD",
		CurrencySymbol: "LD",
		Phone:          "+218",
		Name:           "Libya",
	},
	Country{
		Code:           "LI",
		Currency:       "CHF",
		CurrencySymbol: "CHF",
		Phone:          "+423",
		Name:           "Liechtenstein",
	},
	Country{
		Code:           "LT",
		Currency:       "LTL",
		CurrencySymbol: "Lt",
		Phone:          "+370",
		Name:           "Lithuania",
	},
	Country{
		Code:           "LU",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+352",
		Name:           "Luxembourg",
	},
	Country{
		Code:           "MO",
		Currency:       "MOP",
		CurrencySymbol: "MOP$",
		Phone:          "+853",
		Name:           "Macau SAR China",
	},
	Country{
		Code:           "MK",
		Currency:       "MKD",
		CurrencySymbol: "ден",
		Phone:          "+389",
		Name:           "Macedonia",
	},
	Country{
		Code:           "MG",
		Currency:       "MGA",
		CurrencySymbol: "Ar",
		Phone:          "+261",
		Name:           "Madagascar",
	},
	Country{
		Code:           "MW",
		Currency:       "MWK",
		CurrencySymbol: "MK",
		Phone:          "+265",
		Name:           "Malawi",
	},
	Country{
		Code:           "MY",
		Currency:       "MYR",
		CurrencySymbol: "RM",
		Phone:          "+60",
		Name:           "Malaysia",
	},
	Country{
		Code:           "MV",
		Currency:       "MVR",
		CurrencySymbol: "Rf",
		Phone:          "+960",
		Name:           "Maldives",
	},
	Country{
		Code:           "ML",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+223",
		Name:           "Mali",
	},
	Country{
		Code:           "MT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+356",
		Name:           "Malta",
	},
	Country{
		Code:           "MH",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+692",
		Name:           "Marshall Islands",
	},
	Country{
		Code:           "MQ",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+596",
		Name:           "Martinique",
	},
	Country{
		Code:           "MR",
		Currency:       "MRO",
		CurrencySymbol: "UM",
		Phone:          "+222",
		Name:           "Mauritania",
	},
	Country{
		Code:           "MU",
		Currency:       "MUR",
		CurrencySymbol: "₨",
		Phone:          "+230",
		Name:           "Mauritius",
	},
	Country{
		Code:           "YT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+262",
		Name:           "Mayotte",
	},
	Country{
		Code:           "MX",
		Currency:       "MXN",
		CurrencySymbol: "$",
		Phone:          "+52",
		Name:           "Mexico",
	},
	Country{
		Code:           "FM",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+691",
		Name:           "Micronesia, Federated States Of",
	},
	Country{
		Code:           "MI",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1808",
		Name:           "Midway Island",
	},
	Country{
		Code:           "MD",
		Currency:       "MDL",
		CurrencySymbol: "lei",
		Phone:          "+373",
		Name:           "Moldova",
	},
	Country{
		Code:           "MC",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+377",
		Name:           "Monaco",
	},
	Country{
		Code:           "MN",
		Currency:       "MNT",
		CurrencySymbol: "₮",
		Phone:          "+976",
		Name:           "Mongolia",
	},
	Country{
		Code:           "ME",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+382",
		Name:           "Montenegro",
	},
	Country{
		Code:           "MS",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1664",
		Name:           "Montserrat",
	},
	Country{
		Code:           "MA",
		Currency:       "MAD",
		CurrencySymbol: "MAD",
		Phone:          "+212",
		Name:           "Morocco",
	},
	Country{
		Code:           "MZ",
		Currency:       "MZN",
		CurrencySymbol: "MT",
		Phone:          "+258",
		Name:           "Mozambique",
	},
	Country{
		Code:           "NA",
		Currency:       "NAD",
		CurrencySymbol: "$",
		Phone:          "+264",
		Name:           "Namibia",
	},
	Country{
		Code:           "NR",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+674",
		Name:           "Nauru",
	},
	Country{
		Code:           "NP",
		Currency:       "NPR",
		CurrencySymbol: "₨",
		Phone:          "+977",
		Name:           "Nepal",
	},
	Country{
		Code:           "NL",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+31",
		Name:           "Netherlands",
	},
	Country{
		Code:           "AN",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+599",
		Name:           "Netherlands Antilles",
	},
	Country{
		Code:           "NC",
		Currency:       "XPF",
		CurrencySymbol: "₣",
		Phone:          "+687",
		Name:           "New Caledonia",
	},
	Country{
		Code:           "NZ",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+64",
		Name:           "New Zealand",
	},
	Country{
		Code:           "NI",
		Currency:       "NIO",
		CurrencySymbol: "C$",
		Phone:          "+505",
		Name:           "Nicaragua",
	},
	Country{
		Code:           "NE",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+227",
		Name:           "Niger",
	},
	Country{
		Code:           "NG",
		Currency:       "NGN",
		CurrencySymbol: "₦",
		Phone:          "+234",
		Name:           "Nigeria",
	},
	Country{
		Code:           "NU",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+683",
		Name:           "Niue",
	},
	Country{
		Code:           "NF",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+672",
		Name:           "Norfolk Island",
	},
	Country{
		Code:           "KP",
		Currency:       "KPW",
		CurrencySymbol: "₩",
		Phone:          "+850",
		Name:           "North Korea",
	},
	Country{
		Code:           "MP",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1670",
		Name:           "Northern Mariana Islands",
	},
	Country{
		Code:           "NO",
		Currency:       "NOK",
		CurrencySymbol: "kr",
		Phone:          "+47",
		Name:           "Norway",
	},
	Country{
		Code:           "OM",
		Currency:       "OMR",
		CurrencySymbol: "﷼",
		Phone:          "+968",
		Name:           "Oman",
	},
	Country{
		Code:           "PK",
		Currency:       "PKR",
		CurrencySymbol: "₨",
		Phone:          "+92",
		Name:           "Pakistan",
	},
	Country{
		Code:           "PW",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+680",
		Name:           "Palau",
	},
	Country{
		Code:           "PA",
		Currency:       "PAB",
		CurrencySymbol: "B/.",
		Phone:          "+507",
		Name:           "Panama",
	},
	Country{
		Code:           "PG",
		Currency:       "PGK",
		CurrencySymbol: "K",
		Phone:          "+675",
		Name:           "Papua New Guinea",
	},
	Country{
		Code:           "PY",
		Currency:       "PYG",
		CurrencySymbol: "Gs",
		Phone:          "+595",
		Name:           "Paraguay",
	},
	Country{
		Code:           "PE",
		Currency:       "PEN",
		CurrencySymbol: "S/.",
		Phone:          "+51",
		Name:           "Peru",
	},
	Country{
		Code:           "PH",
		Currency:       "PHP",
		CurrencySymbol: "₱",
		Phone:          "+63",
		Name:           "Philippines",
	},
	Country{
		Code:           "PN",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+870",
		Name:           "Pitcairn Islands",
	},
	Country{
		Code:           "PL",
		Currency:       "PLN",
		CurrencySymbol: "zł",
		Phone:          "+48",
		Name:           "Poland",
	},
	Country{
		Code:           "PT",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+351",
		Name:           "Portugal",
	},
	Country{
		Code:           "PR",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1787",
		Name:           "Puerto Rico",
	},
	Country{
		Code:           "QA",
		Currency:       "QAR",
		CurrencySymbol: "﷼",
		Phone:          "+974",
		Name:           "Qatar",
	},
	Country{
		Code:           "RE",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+262",
		Name:           "Reunion",
	},
	Country{
		Code:           "RO",
		Currency:       "RON",
		CurrencySymbol: "lei",
		Phone:          "+40",
		Name:           "Romania",
	},
	Country{
		Code:           "RU",
		Currency:       "RUB",
		CurrencySymbol: "₽",
		Phone:          "+7",
		Name:           "Russia",
	},
	Country{
		Code:           "RW",
		Currency:       "RWF",
		CurrencySymbol: "R₣",
		Phone:          "+250",
		Name:           "Rwanda",
	},
	Country{
		Code:           "BL",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+590",
		Name:           "Saint Barthelemy",
	},
	Country{
		Code:           "SH",
		Currency:       "SHP",
		CurrencySymbol: "£",
		Phone:          "+290",
		Name:           "Saint Helena",
	},
	Country{
		Code:           "KN",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1869",
		Name:           "Saint Kitts and Nevis",
	},
	Country{
		Code:           "LC",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1758",
		Name:           "Saint Lucia",
	},
	Country{
		Code:           "MF",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+1",
		Name:           "Saint Martin",
	},
	Country{
		Code:           "PM",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+508",
		Name:           "Saint Pierre and Miquelon",
	},
	Country{
		Code:           "ST",
		Currency:       "STD",
		CurrencySymbol: "Db",
		Phone:          "+239",
		Name:           "Saint tome and principle",
	},
	Country{
		Code:           "VC",
		Currency:       "XCD",
		CurrencySymbol: "$",
		Phone:          "+1784",
		Name:           "Saint Vincent and the Grenadines",
	},
	Country{
		Code:           "WS",
		Currency:       "WST",
		CurrencySymbol: "WS$",
		Phone:          "+684",
		Name:           "Samoa",
	},
	Country{
		Code:           "SM",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+378",
		Name:           "San Marino",
	},
	Country{
		Code:           "SA",
		Currency:       "SAR",
		CurrencySymbol: "﷼",
		Phone:          "+966",
		Name:           "Saudi Arabia",
	},
	Country{
		Code:           "SN",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+221",
		Name:           "Senegal",
	},
	Country{
		Code:           "RS",
		Currency:       "RSD",
		CurrencySymbol: "Дин.",
		Phone:          "+381",
		Name:           "Serbia",
	},
	Country{
		Code:           "SC",
		Currency:       "SCR",
		CurrencySymbol: "₨",
		Phone:          "+248",
		Name:           "Seychelles",
	},
	Country{
		Code:           "SL",
		Currency:       "SLL",
		CurrencySymbol: "Le",
		Phone:          "+232",
		Name:           "Sierra Leone",
	},
	Country{
		Code:           "SG",
		Currency:       "SGD",
		CurrencySymbol: "$",
		Phone:          "+65",
		Name:           "Singapore",
	},
	Country{
		Code:           "SX",
		Currency:       "ANG",
		CurrencySymbol: "ƒ",
		Phone:          "+721",
		Name:           "Sint Maarten",
	},
	Country{
		Code:           "SK",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+421",
		Name:           "Slovakia",
	},
	Country{
		Code:           "SI",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+386",
		Name:           "Slovenia",
	},
	Country{
		Code:           "SB",
		Currency:       "SBD",
		CurrencySymbol: "$",
		Phone:          "+677",
		Name:           "Solomon Islands",
	},
	Country{
		Code:           "ZA",
		Currency:       "ZAR",
		CurrencySymbol: "R",
		Phone:          "+27",
		Name:           "South Africa",
	},
	Country{
		Code:           "GS",
		Currency:       "GBP",
		CurrencySymbol: "£",
		Phone:          "+500",
		Name:           "South Georgia and the South Sandwich Islands",
	},
	Country{
		Code:           "KR",
		Currency:       "KRW",
		CurrencySymbol: "₩",
		Phone:          "+82",
		Name:           "South Korea",
	},
	Country{
		Code:           "SS",
		Currency:       "SSP",
		CurrencySymbol: "£",
		Phone:          "+211",
		Name:           "South Sudan",
	},
	Country{
		Code:           "ES",
		Currency:       "EUR",
		CurrencySymbol: "€",
		Phone:          "+34",
		Name:           "Spain",
	},
	Country{
		Code:           "LK",
		Currency:       "LKR",
		CurrencySymbol: "₨",
		Phone:          "+94",
		Name:           "Sri Lanka",
	},
	Country{
		Code:           "SD",
		Currency:       "SDG",
		CurrencySymbol: "ج.س.",
		Phone:          "+249",
		Name:           "Sudan",
	},
	Country{
		Code:           "SR",
		Currency:       "SRD",
		CurrencySymbol: "$",
		Phone:          "+597",
		Name:           "Suriname",
	},
	Country{
		Code:           "SJ",
		Currency:       "NOK",
		CurrencySymbol: "kr",
		Phone:          "+47",
		Name:           "Svalbard",
	},
	Country{
		Code:           "SZ",
		Currency:       "SZL",
		CurrencySymbol: "E",
		Phone:          "+268",
		Name:           "Swaziland",
	},
	Country{
		Code:           "SE",
		Currency:       "SEK",
		CurrencySymbol: "kr",
		Phone:          "+46",
		Name:           "Sweden",
	},
	Country{
		Code:           "CH",
		Currency:       "CHF",
		CurrencySymbol: "CHF",
		Phone:          "+41",
		Name:           "Switzerland",
	},
	Country{
		Code:           "SY",
		Currency:       "SYP",
		CurrencySymbol: "£",
		Phone:          "+963",
		Name:           "Syria",
	},
	Country{
		Code:           "TW",
		Currency:       "TWD",
		CurrencySymbol: "NT$",
		Phone:          "+886",
		Name:           "Taiwan",
	},
	Country{
		Code:           "TJ",
		Currency:       "TJS",
		CurrencySymbol: "SM",
		Phone:          "+992",
		Name:           "Tajikistan",
	},
	Country{
		Code:           "TZ",
		Currency:       "TZS",
		CurrencySymbol: "TSh",
		Phone:          "+255",
		Name:           "Tanzania",
	},
	Country{
		Code:           "TH",
		Currency:       "THB",
		CurrencySymbol: "฿",
		Phone:          "+66",
		Name:           "Thailand",
	},
	Country{
		Code:           "TG",
		Currency:       "XOF",
		CurrencySymbol: "CFA",
		Phone:          "+228",
		Name:           "Togo",
	},
	Country{
		Code:           "TK",
		Currency:       "NZD",
		CurrencySymbol: "$",
		Phone:          "+690",
		Name:           "Tokelau",
	},
	Country{
		Code:           "TO",
		Currency:       "TOP",
		CurrencySymbol: "T$",
		Phone:          "+676",
		Name:           "Tonga",
	},
	Country{
		Code:           "TT",
		Currency:       "TTD",
		CurrencySymbol: "TT$",
		Phone:          "+1868",
		Name:           "Trinidad and Tobago",
	},
	Country{
		Code:           "TN",
		Currency:       "TND",
		CurrencySymbol: "د.ت",
		Phone:          "+216",
		Name:           "Tunisia",
	},
	Country{
		Code:           "TR",
		Currency:       "TRY",
		CurrencySymbol: "₺",
		Phone:          "+90",
		Name:           "Turkey",
	},
	Country{
		Code:           "TM",
		Currency:       "TMT",
		CurrencySymbol: "T",
		Phone:          "+7370",
		Name:           "Turkmenistan",
	},
	Country{
		Code:           "TC",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1649",
		Name:           "Turks and Caicos Islands",
	},
	Country{
		Code:           "TV",
		Currency:       "AUD",
		CurrencySymbol: "$",
		Phone:          "+688",
		Name:           "Tuvalu",
	},
	Country{
		Code:           "UG",
		Currency:       "UGX",
		CurrencySymbol: "USh",
		Phone:          "+256",
		Name:           "Uganda",
	},
	Country{
		Code:           "UA",
		Currency:       "UAH",
		CurrencySymbol: "₴",
		Phone:          "+380",
		Name:           "Ukraine",
	},
	Country{
		Code:           "AE",
		Currency:       "AED",
		CurrencySymbol: "د.إ",
		Phone:          "+971",
		Name:           "United Arab Emirates",
	},
	Country{
		Code:           "UK",
		Currency:       "AED",
		CurrencySymbol: "د.إ",
		Phone:          "+44",
		Name:           "United Kingdom",
	},
	Country{
		Code:           "UM",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1",
		Name:           "United States Minor Outlying Islands",
	},
	Country{
		Code:           "US",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1",
		Name:           "United States",
	},
	Country{
		Code:           "UY",
		Currency:       "UYU",
		CurrencySymbol: "$U",
		Phone:          "+598",
		Name:           "Uruguay",
	},
	Country{
		Code:           "UZ",
		Currency:       "UZS",
		CurrencySymbol: "лв",
		Phone:          "+998",
		Name:           "Uzbekistan",
	},
	Country{
		Code:           "VU",
		Currency:       "VUV",
		CurrencySymbol: "VT",
		Phone:          "+678",
		Name:           "Vanuatu",
	},
	Country{
		Code:           "VE",
		Currency:       "VEF",
		CurrencySymbol: "Bs",
		Phone:          "+58",
		Name:           "Venezuela",
	},
	Country{
		Code:           "VN",
		Currency:       "VND",
		CurrencySymbol: "₫",
		Phone:          "+84",
		Name:           "Vietnam",
	},
	Country{
		Code:           "VI",
		Currency:       "USD",
		CurrencySymbol: "$",
		Phone:          "+1340",
		Name:           "Virgin Islands",
	},
	Country{
		Code:           "WF",
		Currency:       "XPF",
		CurrencySymbol: "₣",
		Phone:          "+681",
		Name:           "Wallis and Futuna",
	},
	Country{
		Code:           "EH",
		Currency:       "MAD",
		CurrencySymbol: "MAD",
		Phone:          "+212",
		Name:           "Western Sahara",
	},
	Country{
		Code:           "YE",
		Currency:       "YER",
		CurrencySymbol: "﷼",
		Phone:          "+967",
		Name:           "Yemen",
	},
	Country{
		Code:           "ZM",
		Currency:       "ZMK",
		CurrencySymbol: "﷼",
		Phone:          "+260",
		Name:           "Zambia",
	},
	Country{
		Code:           "ZW",
		Currency:       "ZWL",
		CurrencySymbol: "﷼",
		Phone:          "+263",
		Name:           "Zimbabwe",
	},
}
